--1
--SELECT PRODUCT_NAME FROM ORDERS

--2
--SELECT * FROM CUSTOMERS
--3
--SELECT PRODUCT_NAME, AMOUNT,DATE_ORDER FROM ORDERS
--4
--SELECT PRODUCT_NAME, DATE_ORDER FROM ORDERS
--ORDER BY DATE_ORDER ASC
--5
--SELECT DISTINCT ID_CUSTOMER FROM ORDERS
--6
--SELECT * FROM ORDERS
--WHERE PRODUCT_NAME='Apple MacBook Air 13"'
--7
--SELECT ID_CUSTOMER,DATE_ORDER,AMOUNT FROM ORDERS
--WHERE AMOUNT > 2 AND ID_CUSTOMER IS NOT NULL
--8
--SELECT * FROM ORDERS
--WHERE YEAR(DATE_ORDER) BETWEEN 2014 AND 2014
--9
--SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS
--WHERE LASTNAME LIKE 'Ê%'
--10
--SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS
--WHERE FIRSTNAME LIKE '%à'
--11
--SELECT FIRSTNAME, LASTNAME FROM CUSTOMERS
--WHERE LASTNAME LIKE '______'
--12
--SELECT PRODUCT_NAME FROM ORDERS
--WHERE PRODUCT_NAME NOT IN('Asus PU301LA','HP 255 G3')
--13
--SELECT LASTNAME FROM CUSTOMERS 
--WHERE ADDRESS IS NULL
--14
--SELECT ID, PRODUCT_NAME, AMOUNT, PRODUCT_PRICE*AMOUNT AS SUM_PAID FROM ORDERS
--15
--SELECT * FROM ORDERS
--WHERE YEAR(DATE_ORDER) <2015








