--1
--CREATE DATABASE NORTHBUKIT
--2
--USE NORTHBUKIT

--CREATE TABLE CUSTOMERS (ID INT PRIMARY KEY NOT NULL,
--FIRSTNAME VARCHAR(30),
--LASTNAME VARCHAR(30))
--3
--ALTER TABLE CUSTOMERS
--ADD ADDRESS VARCHAR(100)
--4
--CREATE TABLE ORDERS(ID INT,
--PRODUCT_NAME VARCHAR(30),
--PRODUCT_PRICE NUMERIC(8,2),
--DATE_ORDER DATE,
--ID_CUSTOMER INT)
--5
--ALTER TABLE ORDERS ADD AMOUNT INT
--6
--ALTER TABLE ORDERS
--ALTER COLUMN ID INT NOT NULL
--ALTER TABLE ORDERS
--ADD CONSTRAINT ID PRIMARY KEY(ID)
--7




